# Generated by Django 4.1.7 on 2023-03-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrossfitApp', '0003_remove_review_category_review_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitors',
            name='competition_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrossfitApp.competition'),
        ),
    ]
