# Generated by Django 4.1.5 on 2023-03-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrossfitApp', '0005_competitors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='competitorImages/'),
        ),
    ]
