# Generated by Django 4.1.7 on 2023-03-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrossfitApp', '0009_alter_competitors_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='datetime',
        ),
    ]
